version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '10101:10101'
    env_file:
      - environments/docker.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    restart: always
    ports:
      - '10110:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kimos
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=kimos